version: 1
# stages
stages:
  main:
    inbox:
      - slot:
        tag: get_resource(stuff_a_txtfiles, "recommended")
        label: stuff_a
        pattern: "*.txt => /textfiles/"
    outbox:
      - slot: 
        label: stuff_b
        pattern: "*.txt => /textfiles/"
