version: 1

# mb store get LUA/2de [best]
inbox:
  LUA:
    tag: worst
  #LUA2:
  #  tag: worst
  #LUA:
  #  tag: super

  #inbox:
#  - LUA:
#      tag: best

#stage:
#  MYLUA:
#    - *.exe => /bin/

#$(MB_LUA_ROOT_RELPATH)\Release


outbox:
  PROJA:
    - "*.txt -> /rel/"
